### PR TITLE
Z axis limits

### PR DESCRIPTION
**Pull request by Orob-Maslow**
What does this add:
Button in Actions modal page to open modal to set software limits on z axis movement.  settings are cleared by pressing the clear button, then new ones are saved by moving the z axis to the upper limit, pressing the upper button, moving to the lower limit, pressing the lower limit button.  the get limit option is not yet implemented but may be in a future commit.  this pull has the basic functionality.  
The clear button sends B19 to the controller
The upper limit sends B17 to the controller
The lower limit sends B18 to the controller
No values are stored in webcontrol.  Commands are issued to the arduino (must be newer firmware version with these new B command features.
image
image
This is part of Feature Request #136 https://github.com/WebControlCNC/WebControl/issues/136

### CODE REVIEW

**Comment by madgrizzle** [comment]
How does the user move the z-axis?  Do they need to exit and come back to this page?

**Comment by Orob-Maslow** [comment]
They would need to exit.  Perhaps a distance input and an up/down button would be most useful.  I'll add that.

**Comment by Orob-Maslow** [comment]
how does this one look?

image

**Comment by Orob-Maslow** [comment]
I trimmed it a bit and I think this one is better.
image

**Comment by madgrizzle** [comment]
What happens when someone uses these commands with an old firmware?

**Comment by Orob-Maslow** [comment]
nothing.  the B commands return with: 
image

**Comment by Orob-Maslow** [comment]
This is how the mobile one renders:

Screenshot_20200522-190614

**Comment by Orob-Maslow** [comment]
I suppose we could have the Z axis limit button only available if the correct firmware version is available or we could put in a settings toggle to enable it in advanced settings.  Since webcontrol already checks the firmware number, that variable should be available to check.

**Comment by Orob-Maslow** [comment]
Newer commit adds:
-Firmware check:  Must be greater than 1.26 or button does not appear.
-Mobile page with fewer columns.
It also has abbreviated test for size and readability.

**Comment by gb0101010101** [comment]
Nice work @Orob-Maslow. Only thing I would change is variable name `firmwareVersionNewEnough` to be more descriptive. e.g. `firmwareSupportsZLimit`
Just got my Malsow hardware home and will test this and firmware changes soon.

**Comment by Orob-Maslow** [comment]
bump.  Review required for merge.  Can someone review this so it can be closed out?

**Comment by Orob-Maslow** [comment]
bump... anyone out there?

**Review by rolambert — APPROVED** [review]
no issues of note, keep track of the time.sleep(.5)

**Pull request merged**
