### PR TITLE
Integrate changes from the experimental branch

### PR DESCRIPTION
**Pull request by emilecantin**

### CODE REVIEW

**Comment by gb0101010101** [comment]
None of this should be committed. The current code in `master` is correct.

AFAIK this was caused by an unexpected merge of `experimental` branch into `master` that has already been fully reverted.

Please let me know if I am missing something and perhaps provide some context to the source of this PR.

**Comment by emilecantin** [comment]
@gb0101010101 Well, to quote you from 2 days ago, on #118 :

> Just a reminder that these changes have not been committed to Master. Others are submitting PRs based on Master that are causing merge conflicts. Really want this code incorporated as it fixed many issues and required extensive testing.

I opened this PR to track work on that, but you can close it if it's not needed anymore.

**Comment by madgrizzle** [comment]
I recall trying to work with @gb0101010101's PR and totally hosed up github due to my lack of github experience.  I somehow fixed it and maybe this is an artifact of it.  We still need to incorporate @gb0101010101's work.. just don't know how to do it.

**Comment by emilecantin** [comment]
Okay, so did I not choose the correct branches when creating this? If not, let @gb0101010101 create the correct PR to track this work, a comment in a _very_ stale, closed PR is not a good place to follow that work; we'll forget about it in just a few days (I know I will).

**Comment by gb0101010101** [comment]
@emilecantin

Sorry for confusion. I think I see what is going on here. You created a PR by merging `experimental` into `master`. Somehow the `experimental` branch got messed up and no longer contains the changes from #118 even though they were committed in https://github.com/WebControlCNC/WebControl/commit/868cf8831a62fbc71ee1829dc86ccec7213f39e6

I thought you were asking me to review changes that needed to happen before #118 is committed.

The original PRs merged into #118 are #108 #112 #115. None of these are in `master`.

I will try to resubmit these later.

**Comment by emilecantin** [comment]
Yeah, it does seem like the branches got messed up; I originally thought it was just a simple dangling branch that needed to be merged.

Please open a new PR on master with the changes you'd like to see, and we'll track that work there.

Note: it looks like your original pull requests were merged into master, if the changes aren't there anymore it's probably because of a revert. These are a pain to undo, but I believe with a `cherry-pick` operation to get the specific commits that were in these PRs, you'll be able to re-apply these changes on the current master.

**Comment by gb0101010101** [comment]
I think I have a clean merge in #117 and will test it later today.

**Pull request closed without merging**
