### PR TITLE
Optical calibration

### PR DESCRIPTION
**Pull request by madgrizzle**
merging in opticalCalibration to the master branch

### CODE REVIEW

**Comment by madgrizzle** [comment]
I don't know what I'm doing an worried I'll do something wrong.  I'm not sure what to do about the conflicts.. I **think** I'm merging changes from optical calibration into the master branch.  Can you verify this?

**Comment by johnboiles** [comment]
This looks right to me but I guess we have some changes in master that are not in the opticalCalibration branch. Since no one else is really using this repo I think it’d also be fine to just blow away the master branch and force push the opticalCalibration branch to master.

```
git checkout opticalCalibration
git pull origin opticalCalibration
git branch -D master
git checkout -b master
git push -f origin master
```

This is generally bad practice but since it’s just the two of us on this repo I think it’s fine.

**Comment by madgrizzle** [comment]
Mind doing that?  I'm scared :)

**Comment by johnboiles** [comment]
Sure! I'll do it in the next hour or so when kiddos go down for a nap

**Comment by madgrizzle** [comment]
Sounds good, I assume I should just close this PR.  I'm adding a new file to webcontrol so that will handle sending messages to webmcp so instead of using print, you add whatever to the mcpqueue and it will print it to the terminal but also show up on webmcp.. handy so you don't have to have be in ssh to see printed messages.  Should be there before nap time.

**Comment by johnboiles** [comment]
👍 keep this PR open for now, maybe i'll use it to merge

**Pull request merged**
