### PR TITLE
Positioning mode tracking fixes: 

### PR DESCRIPTION
**Pull request by gb0101010101**
1. Add comments to describe states in data.py
2. Save paused positioning mode after gcode message has been sent to serialInstance. This is incase the message send fails.
3. Fix restore positioning mode logic in resumeRun. pausedPositioningMode can be 0 or 1 and must be restored in both cases. So previous logic does not makes sense:
```
if self.data.pausedPositioningMode == 1: 
  self.data.gcode_queue.put("G91 ")
```
4. Clear pausedPositioningMode saved state after restoration. To make sure it does not get used later by mistake.
5. Always restore paused positioning in pauseRun (if current position mode has changed). _self.data.manualZAxisAdjust_ was not True in _resumeRun_ when I tested by pausing, moving z axis, and resuming.

### CODE REVIEW

**Comment by madgrizzle** [comment]
1.  Good.

2.  Good also.

3. So when the cut is manually paused, the current positioning mode is saved to self.data.pausedPositioningMode.  When resuming, we need to send the code that will get it back to that mode.  But in line 574/575, we already put it in absolute mode (G90) so we only need to put it into incremental mode (G91) if it was previously in that mode.  That's the reason behind the logic.

I don't understand python and threads well enough so I worry about race conditions and was concerned about using self.data.positioningMode in actions.py because I don't know how long it takes for something put in the gcode_queue to make its way through processing to update self.data.positioningMode.  I already knew for certain that it was put in G90 mode so if I needed to send G91 to get back to that mode, then that would be based on self.data.pausedPositioningMode and checking self.data.positioningMode wasn't needed.  

Also, all of this needs to happen before self.data.uploadFlag is set to 1, which allows serialPortThread to resume sending the gcode file.  If the commands are in gcode_queue before the flag is set, then they will get issued before it resumes sending the file (serialPortThread.py, line 319).  Otherwise, gcode from the file could be sent before its put back in the correct positioning mode.

Also, my comment line in the code was wrong.. said compare against 0 and not 1.

4. I'm not sure it's needed, but I'm also not sure its harmful.  The only time pausedPositioningMode is set is when pauseRun and I believe the only time pausedRun is called is when a user presses pause.  And the only time pausedPositioningMode is checked is in resumeRun which is only called when the user presses resume.  

5.  This part I agree with.  I confused self.sendGCodePositionUpdate with self.processGCode which handles the G90/G91 thing itself.  However, the change needs to happen before self.data.uploadFlag is set to 1.

Let me know if this makes sense.

**Comment by madgrizzle** [comment]
Also, I could be wrong.. I've been wrong before.

**Comment by gb0101010101** [comment]
OK, there seems to be problems with queues running asynchronously. 

## Trigger when Maslow executes gcode

First I need to figure where these things should be triggered:
The _positioningMode_ change is triggered when SerialPortThread writes Gcode.
BUT
The _ToolChange_ is triggered when UIProcessor gets a "Tool Change:" message.

Right now it looks like _positioningMode_ is saved before the Malsow board executes the G90/G91 code. Where as _ToolChange_ is triggered AFTER the Malsow board has execute M6 gcode. Is that true?
If so then I think these things should be triggered the same way.

## Tool change workflow 

Tool Change does not run _pauseRun_ Action so all the self.data.paused* variables are not saved. I added `self.app.data.pausedPositioningMode = self.app.data.positioningMode` to _UIProcessor_ temporarily to make things work with minimal code change but really the tool change should run the _pauseRun_ action for consistency rather then saving all the paused values itself.

## ResumeRun Action gcode
Reorganized this to have all paused values restored wether it was a manual pause or a tool change.

gcode put to  _self.data.gcode_queue_ does not execute immediately. I tested moving lots of code around to see if other things like _uploadFlag_  or _self.data.quick_queue.put("~")_ affected it but there was no difference. The gcode here sees to execute only after the action is completed.
 
I added `self.data.positioningMode = 0` under `self.data.gcode_queue.put("G90 ")` to temporarily fix this. All the other paused values are restored correctly without change.

Again The gcode run in this Action should execute immediately.

Interestingly if you click on Frontpage _Pause_ button. The use z-Axis controls they will work even though they are using the same _self.data.gcode_queue_. 

## Test GCode
### Manual Pause:
```
(TEST_POSITION)  
G0 G40 G90  
G21  
G00 X0 Y0 Z0  
(RELATIVE)  
G91  
G00 Z6  
G00 X150 Y150  
(PAUSE_HERE_AND_MOVE_Z)  
G00 X20 Y20  
G00 Z0
```  

### Tool Change:
```
(TEST_POSITION)  
(T1 D=6.35 CR=0 - ZMIN=-19.318 - FLAT END MILL)  
G0 G40 G90  
G21  
G00 X0 Y0 Z0  
(RELATIVE)  
G91  
G00 Z5  
G00 X150 Y150  
(TOOL CHANGE)  
T1 M6  
G00 X20 Y20  
```

**Comment by madgrizzle** [comment]
I'll type more tomorrow.. there's two different pause mechanisms.. one is when the firmware initiates a pause (tool change) and other is user initiates a pause.  .. well, I'll type more tomorrow :)

**Comment by gb0101010101** [comment]
No rush. I will not be able to do anything more till the weekend.

**Comment by madgrizzle** [comment]
> First I need to figure where these things should be triggered:
> The _positioningMode_ change is triggered when SerialPortThread writes Gcode.
> BUT
> The _ToolChange_ is triggered when UIProcessor gets a "Tool Change:" message.
> 
> Right now it looks like _positioningMode_ is saved before the Malsow board executes the G90/G91 code. Where as _ToolChange_ is triggered AFTER the Malsow board has execute M6 gcode. Is that true?
> If so then I think these things should be triggered the same way.

Tool change and user-initiated pause work differently.  With a user-initiated pause, webcontrol just stops sending gcode to the controller.  For tool change, the controller pauses on its own when it sees the M6 gcode command IF the current tool does not equal the new tool.  When this happens, the controller sends a message to groundcontrol/webcontrol and that message is caught and actions are taken.  The controller waits for a resume signal ("~") to be sent before it continues.  Because of an issue in the firmware, I started tracking the current tool to catch when a tool change pause is imminent and stopped sending gcode after the M6 command.  This was needed to overcome issues with the option to buffer gcode in the controller... among other things.

I like the idea of trying to make things consistent considering we now track positioning modes, we just need to make sure it works with the buffering gcode option.  When it was an controller-initiated pause, I set uploadFlag to -1.. so we would need to make sure if we call pauseRun, then it still gets processed (currently, pausedRun only does something if uploadFlag ==1)

> Tool Change does not run _pauseRun_ Action so all the self.data.paused* variables are not saved. I added `self.app.data.pausedPositioningMode = self.app.data.positioningMode` to _UIProcessor_ temporarily to make things work with minimal code change but really the tool change should run the _pauseRun_ action for consistency rather then saving all the paused values itself.

That's the simplest fix for the issue, but I certainly like the idea of improving the process.

> ResumeRun Action gcode

I'll respond once I dig into it further

**Comment by madgrizzle** [comment]
> gcode put to _self.data.gcode_queue_ does not execute immediately. I tested moving lots of code around to see if other things like _uploadFlag_ or _self.data.quick_queue.put("~")_ affected it but there was no difference. The gcode here sees to execute only after the action is completed.
> 
> I added `self.data.positioningMode = 0` under `self.data.gcode_queue.put("G90 ")` to temporarily fix this. All the other paused values are restored correctly without change.

Yes, that's exactly why I did not depend upon self.data.positioningMode in that function.  I knew it was in G90 mode already, so no need to test against it.. but your change works regardless.

> Again The gcode run in this Action should execute immediately.

As I mentioned previously, I don't know enough about python and threads, but its *possible* that if you put a sleep command in right after sending the G90, that it will allow the serialPortThread to run a cycle.  But there's no harm in setting self.data.positioningMode to 0 manually in that function.

**Comment by davidelang** [comment]
On Thu, 23 Jan 2020, madgrizzle wrote:

> Because of an issue in the firmware, I 
> started tracking the current tool to catch when a tool change pause is 
> imminent and stopped sending gcode after the M6 command.  This was needed to 
> overcome issues with the option to buffer gcode in the controller... among 
> other things.

Thinking about our long term hopes (i.e. plans :-) ) to move to grbl derived 
firmware, you may want to look at what grbl does with it's jog functionality. 
It doesn't completely fill the buffer and the firmware looks for special 
characters that require immediate attention (stop, jog, etc) as they arrive in 
the buffer, separte from interpreting the g-code

we may want to look at implementing something similar for at least stop in the 
current firmware (and try to make it compatible)

David Lang

**Comment by madgrizzle** [comment]
I don't know if there's a proper way to test the PR, but I just created a branch in my repo (test1) and pulled in your changes to it.  I'm still new at github.

In the resumeRun function, I moved your new part where the positioning mode is set and then deleted a couple of lines that were no longer needed.   I *think* its cleaner now and makes sense to me, even though I think there is an unreachable line (no harm, no foul though).

When you get a chance, take a look at the test1 branch and the change to actions I committed.  I'll try to test tonight/tomorrow when I can get to a machine with a controller attached.

**Comment by madgrizzle** [comment]
> we may want to look at implementing something similar for at least stop in the current firmware (and try to make it compatible)

The firmware does have a quick_queue for commands like stop and pause that has that functionality.  The problem was specifically with the tool change command.  I can't remember all the specifics (there's a post on the forum... https://forums.maslowcnc.com/t/tool-change-functionality-question-about-ground-control/11626) but the issue was that some change was made to the firmware (probably because of buffering gcode option) that unintentionally made it impossible to resume after a tool change.  So instead of trying to fix the firmware (and all that entails), I just worked around it in webcontrol.  It's still broken in ground control.

**Comment by madgrizzle** [comment]
> Thinking about our long term hopes (i.e. plans :-) ) to move to grbl derived firmware, you may want to look at what grbl does with it's jog functionality. It doesn't completely fill the buffer and the firmware looks for special characters that require immediate attention (stop, jog, etc) as they arrive in the buffer, separte from interpreting the g-code

I've been *thinking* about grbl and marlin and how to get them to work in webcontrol.  It's a different approach than that of maslow and I'm still trying to wrap my head around it.  I would almost defer to using something like cnc.js but I use cnc.js and its nowhere near as user friendly as ground control/webcontrol and then I'd think of the headaches trying to help users that tend to have a hard time even opening a file :)

**Comment by davidelang** [comment]
we probably need to make the firmware handle resume like it does stop and pause.

David Lang

**Comment by davidelang** [comment]
On Thu, 23 Jan 2020, madgrizzle wrote:

>> Thinking about our long term hopes (i.e. plans :-) ) to move to grbl derived firmware, you may want to look at what grbl does with it's jog functionality. It doesn't completely fill the buffer and the firmware looks for special characters that require immediate attention (stop, jog, etc) as they arrive in the buffer, separte from interpreting the g-code
>
> I've been *thinking* about grbl and marlin and how to get them to work in 
> webcontrol.  It's a different approach than that of maslow and I'm still 
> trying to wrap my head around it.  I would almost defer to using something 
> like cnc.js but I use cnc.js and its nowhere near as user friendly as ground 
> control/webcontrol and then I'd think of the headaches trying to help users 
> that tend to have a hard time even opening a file :)

grbl should be a pretty trivial change in WC, but grbl would need to be taught 
the kinematics, servo control, and the equivalent of (at least some of) our B 
commands.

David Lang

**Comment by madgrizzle** [comment]
If you limit the feature set supported to match only the features we have in the current firmware, it would be a lot easier.. not trivial, but easier.  However, I want to look at more options, such as workspaces... maybe making webcontrol more open and not just maslow-centric.  That's what I'm trying to wrap my head around.

**Comment by madgrizzle** [comment]
@gb0101010101, take a look at the test1 branch.  I've done some testing on it and I think it works.  I discovered today that tool change was broke again and think its working now.

**Comment by gb0101010101** [comment]
Checkout out test branch and it is working the same as mine. This is still not ideal though. The gcode in Actions should be processed real time. Can't figure out why its not.

**Comment by madgrizzle** [comment]
I think if you put a sleep in after each gcode, it will give python time to run the serialPortThread thread.  It has to do with python threading library.  When I started developing webcontrol, I couldn't figure out why my threads were blocking and discovered they unblocked if I added a small sleep command.  I think using something like python's multiprocessing would work better, but it is what it is for the time being.

https://docs.python.org/2/glossary.html#term-global-interpreter-lock

**Comment by madgrizzle** [comment]
So, I think the issue with threads is related to the use of gevent and monkey.patch_all().. which I apparently need in order to get the websocket communications working.

https://stackoverflow.com/questions/9192539/using-gevent-monkey-patching-with-threading-makes-thread-work-serially

**Comment by gb0101010101** [comment]
Success!! Got the gcode_queue sending commands to serial port instantly. Made a LOT of changes and it is not done.

Test branch:
https://github.com/gb0101010101/WebControl/tree/gb0101010101-serial-port-thread
Comparison:
https://github.com/gb0101010101/WebControl/compare/master...gb0101010101:gb0101010101-serial-port-thread?expand=1

- Rewrote SerialPort.py to handle the serial port connection rather than SerialPortThread.  SerialPortThread now only handles input from queues and write to serial port. Before the connection was constantly being opened and closed and had weird code to made it work. The connection is now stable and has not failed once. The thread should terminate when the SerialPort.closeConnection() is used.
- Added code to ignore the thread processing timeout is FakeServo is on. This means you can debug it without it terminating.
- Added queue.task_done() after every queue.get_message() is processed. This may be removing blocking and should allow queue.join() to work which will let code wait until queue has processed all items to that point.
- Moved gevent import to first line in main.py, applied monkey patch immediately and told it to ignore threads. I think this is the main reason it works.
- These changes has also reduced processor use. At max I am seeing 35% when it was previously 45%. 

There are a number of issues that I could use some help on:
- The Controller message queue is not updating real time. Look in console for serial port writes and see that they happen well in advance.
- The FakeServo indication in top right is not showing. It just shows connected.
- The SerialPortThread thread stops when serial port is unplugged and will not resume automatically.
- I have no idea about the serial port instance timeout and the sleep timeouts.
- I have no clue what other ramifications `monkey.patch_all(thread=False)` will have but so far I don't see anything wrong.
- Fair bit of tidying up left.

Almost gave up on this as I spent 5 hours rewriting the serial port code and then somehow lost my whole python IDE workspace with all the changes. Of course I did not upload test code to github so had to start over!

**Comment by madgrizzle** [comment]
Wow.. that's pretty cool.  I'll start looking at it (work has picked up and I have a cold..)  I've been working with @Orob-Maslow on getting gpio to work and looked like the monkey patch was causing issues.  I figured out how to avoid using patch_all and wondered if that would help.  I changed all the time.sleep commands to socketio.sleep commands (look at the No_Monkey branch).  But I don't know what monkey patch does anyway and what telling it to ignore threads does :)

**Comment by madgrizzle** [comment]
SerialPort runs openConnection every 5 seconds.  I used 'schedule' to accomplish it to try to mirror what groundcontrol did.  If you look at the serialPort.py's __init__() you'll see the command to set the schedule and in main.py, you'll see the thread that kicks off the scheduler.  Since you rewrote __init__, you commented out that part so it doesn't run openConnection every 5 seconds.  That's why it won't autoreconnect and why the controller status isn't updated (it gets updated whenever openConnection is run).

But since you've rewritten openConnection some, you probably need to make a new function that you put on the schedule to run and watch if the connection is closed.. if it is, then call open connection.. and include the status update as well.

Also, it won't attempt to reopen if you have fake_servo enabled on your controller.  Webcontrol/groundcontrol looks for regular data from the controller and if it doesn't see any for two seconds, it assumes the controller is disconnected.  In that part of the serialPortThread that tested that, you added a conditional check and only did that test if fake_servo was disabled.

I made a test2 branch on my repo with your changes and added a few things to get it going.  It updates the status every 5 seconds (see the testConnection() function) and tries to reopen the connection if lost, but it errors on trying to open the port..

>Error opening serial port: could not open port 'COM9': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

https://github.com/madgrizzle/WebControl/tree/test2

**Comment by gb0101010101** [comment]
@madgrizzle Thanks for the info.

Got more working and am very close to having it all done. An _Alarm_ is now raised when the connection is lost. I did this with a read exception that uses the serial instance timeout (0.25) rather then tracking the time taken to execute the getMessage function. This allows for debugging as its only triggered when the serial port takes too long to respond and not if we take too long stepping through the code.

The reconnect is handled by the _Stop_ button using serialPort.clearAlarm() and does not use a scheduler to check connection. The only problem right now is that reconnecting often does not succeed on the first attempt because the USB device may still be busy. This throws another _Alarm_. So you end up having to click the _Stop_ button more than once to clear the alarms. 

Check it out and let me know what problems you experience.

Also could you point me to code that handles:
```
self.data.ui_queue1.put("Action", "connectionStatus",
  {'status': 'connected', 'port': self.data.comport, 'fakeServoStatus': self.data.fakeServoStatus})
```
I cannot seem to find it in UIProcessor.py. I want to see how the WebControl (top right) _Connection Status Button_ is functioning.

Thanks.

**Comment by madgrizzle** [comment]
Line 157 calls process action that then parses the json put in ui_queue1 and sends the appropriate message to the clients.  Remember, all of this was an evolution of code so it might not seem the most intuitive way to do things.

**Pull request merged**
