### PR TITLE
Desktop and Mobile UI improvements

### PR DESCRIPTION
**Pull request by gb0101010101**
Made a number of changes to the Desktop and Mobile UI:

**Common:**
1 - Frontpage - Added feather for _Define Home_ button - uses _Save_ and _Home_ icons
2 - Zaxis modal - Added feather icons for _Raise_, _Lower_, _Def. Zero_, and _Stop_ buttons.
3 - Added .controls class to apply styling to control buttons
4 - Changed _Pause_ button text to be white like all others. 

**Desktop:**
1 - Move 4th row buttons into .controls div so that button size is consistently applied.
2 - Changed "Dist. to Move" label to "Distance" so it will fit. Added CSS to right align and vertically center label. This also centers all buttons so that they align properly in the controls div.

**Mobile:**
1 - Fixed errors: Extra closing div at EOF, Extra closing brackets ")" after onclick actions.
2 - Removed  "Dist. to Move" label as it is not needed ad takes up critical space.
3 - Merged 4th & 5th control button rows so that _Distance_ input, _Units_ button, and _Def. Home_ button are all in one row.
4 - Fixed moveGcode buttons to use 4 col grid.
5 - Hide "WebControl" text from _NavBar_ so that all elements fit on one line.

Could also remove "Controls" heading from mobile view.

### CODE REVIEW

**Comment by madgrizzle** [comment]
Awesome! I'll check it out.

**Comment by madgrizzle** [comment]
I like the updates, but for the change to hide 'Web Control' text from navbar to make it fit on one line, where did you see it not fit?  I'm trying to duplicate.. what size screen causes the problem?

**Comment by gb0101010101** [comment]
Testing on old Galaxy S5. 

**Before**
Menu "hamburger" going to new line.
Webcontrol_UI_before

**After**
Webcontrol_UI_after

**Comment by gb0101010101** [comment]
Should add that Galaxy S5 has screen 1080 x 1920 pixels (~432 ppi density) giving effective 360 x 640 display area. Everything is a good size, is legible, and finger friendly. Reducing sizes is not recommended.

**Comment by gb0101010101** [comment]
Here is a scaled version that more accurately shows the actual size.

Webcontrol_UI_after_scaled

**Comment by madgrizzle** [comment]
Yep, I see it with S5 (must have missed seeing the hamburger move because I'm pretty sure I tried that one). 

I think we should remove "Pos" out of XPos, YPos, etc. to give us more space.. maybe everything will end up on a single line that way.  I can do that once I merge this in.

**Comment by gb0101010101** [comment]
> I think we should remove "Pos" out of XPos, YPos, etc. to give us more space

Oh great, I glad you think so as that was on my list to do.

**Review by madgrizzle — COMMENTED** [review]
works for me

**Review by madgrizzle — APPROVED** [review]

**Comment by gb0101010101** [comment]
Great, thanks. Just went to push XYZ Position update and see you have done that already. Looks much better.

**Comment by madgrizzle** [comment]
Yeah.. lots of what you see is carryover from ground control.. figure at the time to try to make it look as close to it as possible.

**Pull request merged**
