### PR TITLE
Added a velocity readout on the front page

### PR DESCRIPTION
**Pull request by thormj**

### CODE REVIEW

**Comment by thormj** [comment]
Err... did I do that right -- Git-wise?
The patches are independent of each other... so I guess I could rebase it back to master?  Not very familiar with git yet.

**Comment by gb0101010101** [comment]
Hey @thormj can you explain what you are trying to accomplish with these code changes?

What do all of these "states" correspond to and how are they enforced?
- disabler
- gcdisabler
- ndisabler

I do not mean to negate your contribution I just want to understand it. How is the velocity vector used to improve results?
  
Thanks for all input.

**Comment by davidelang** [comment]
displaying the actual velocity can help figure out if you are achieving the feed 
rate that you are looking for (or to understand what's happening when you get 
odd cuts or burning that could be feed rate related.

I have not looked at this patch to see if this is showing instantanious velocity 
or if it's smoothed (and if so over what time period)

But I can see the utility of such a display

David Lang

**Comment by thormj** [comment]
> Hey @thormj can you explain what you are trying to accomplish with these code changes?
> * disabler -- part of the original that means you can't hit the "play" button twice (I added it to everything that said "you can't do this while sending g-code"...
> * gcdisabler -- "g-code send disabler" changed the play button to this so that if you paused it, it wouldn't enable "play from start"
> * ndisabler - "not disabler" -- mainly so the "pause" button is disabled unless you're uploading g-code.

Ack.. that's what I meant by did I bungle the git...  all of the above is part of the "disable buttons" pull request, but I forgot to go back to "master" and restart from that...

**Comment by thormj** [comment]
Okay, I guess GitHub doesn't do threading.  @davidelang , the value displayed is the instantaneous (well delta between the last 2 updates divided by the time between the last 2 updates, with a little extra magic to send the "0 velocity" update once after everything stops)... it becomes pretty solid while moving around (haven't tried to cut with it yet, but since I'm cutting plywood with the spiral upcut, I'm running max speed [I told it 50ipm, and it's running ~30).

Adding an exponential average would be easy-easy... and a time-based one almost easy.

I did throw the "app.data.FeedRate" up there too, but it doesn't look  like anything is updating that field yet, so it just hangs out at 20 for now.  Probably need to add that to UnitsChange and the g-code sender parts.

**Comment by rolambert** [comment]
This is huge! time series data is what i have been looking for!

**Review by rolambert — APPROVED** [review]
so happy to see time series data, why is the timer based on the UI and not another background process? cheers!

**Comment by thormj** [comment]
I'm just figuring out the velocity when the deltas come from the serial port and trigger the UI update.  It's pretty stable on my Maslow, but if it isn't, it wouldn't be hard to add a smoothing filter.

**Comment by thormj** [comment]
Ok, it says it's approved and I can merge it... is there a merge-master or a sprint schedule or ?
I have a corresponding pull request for @madgrizzle 's HoleyFirmware (it's a really smiple patch that adds the PWM and feedrate to the status output) -- if you're not using the FW patch, you get velocity and velocity-setpoint-based-on-gcode (I don't think it will break), but the output PWM will just show up as 15/255 (green).

Corresponding MaslowForums:
https://forums.maslowcnc.com/t/so-i-wanted-to-know-how-much-i-was-using-the-machine-fw-webcontrol-patch/13998
https://forums.maslowcnc.com/t/status-message-format/13992

**Pull request merged**
