### PR TITLE
Fix link to Feather.js in README.md

### PR DESCRIPTION
**Pull request by gb0101010101**
Testing upstream pull request with simple fix to README.md which incorrectly links to feathersjs.com (note plural 'feathers').

Sorry I wrongly executed a Merge pull on my forked repo https://github.com/gb0101010101/WebControl with ID "409f20c". Will not do that again.

### CODE REVIEW

**Comment by blurfl** [comment]
If this is correct, docs/index.md, Line 44 might need the same treatment?

**Comment by gb0101010101** [comment]
Sorry I am just learning GitHub project forking, and pushing changes to upstream repos, so don't know if I am doing it right.

Could you help me by explaining how the _WebControl/docs/index.md_ file is used differently in comparison to the  _WebControl/README.md_ file?

To me it looks like the _WebControl/docs/index.md_ file is an outdated version of the  _WebControl/README.md_ file? If so it should be removed?

The link to https://feathersjs.com/ is certainly wrong, as that is a web-framework that is not being used, so link should be updated in all files that reference it, as the actual library used is at https://github.com/feathericons/feather/ OR https://feathericons.com/

**Comment by blurfl** [comment]
Madgrizzle is the expert here, but I think docs/index.md is what is displayed when the Help/OfflineHelp menu is selected.

**Comment by madgrizzle** [comment]
Yeah, the docs directory appears in both online and offline help.  I'll check out your PR.. looks at first blush to be the correct way.

**Review by madgrizzle — CHANGES_REQUESTED** [review]
I would actually change it to https://feathericons.com since that's their main page.

I can readily make a change myself, but if you don't mind, can you try to update your PR?  I'd like some experience in doing this review and approval process .. I'm too new to a lot of this github stuff.

**Comment by gb0101010101** [comment]
OK both files now point link to https://feathericons.com/

**Review by madgrizzle — APPROVED** [review]
Ok! It'll be included in next release (0.921)

**Pull request merged**
