### PR TITLE
gb0101010101-z-axis-ui: Add 'goto zero' and 'goto safe' buttons with …

### PR DESCRIPTION
**Pull request by gb0101010101**
Adds 'goto zero' and 'goto safe' buttons with new Actions.
Add button colors to 'raise', 'lower', and 'save zero'.
Add more vertical spacing between buttons on mobile to reduce chance of accidental clicks.
Re-order buttons to minimize impact of accidental clicks. 
Improve layout to evenly space and size buttons on both desktop and mobile. 
Add more feather icons to buttons.

z-axis-desktop
z-axis-mobile

### CODE REVIEW

**Comment by gb0101010101** [comment]
Original issue https://github.com/madgrizzle/WebControl/issues/53 can be closed when this is merged.

**Comment by ersdds** [comment]
I actually just installed the new version of the exe file of web control. Looks great! It seems my touch 0 Is greyed out? Am I correct and assuming that this feature is not up and running yet and there are no switches that I have to set to make it work? If that is the case is it possible to run ground control in the background just to use the touch feature only?

**Comment by madgrizzle** [comment]
There's a setting under advanced settings to enable it.  I've never used it.. let me know if it works (or doesn't).

**Comment by gb0101010101** [comment]
"Touch Zero" uses additional hardware that is not included in the Malsow kit. You have to build the hardware yourself and then enable it in settings.

**Comment by ersdds** [comment]
Once again I appreciate you reaching out. I have the hardware and it was
working with Ground Control. I am assuming you were talking about the leads
coming off of AUX 4 ( top and bottom pins). That is connected and the
switch is enabled in Web Control. Unfortunately, nothing happens.

He also noticed what poking around your advanced settings some other
interesting items in there. Do you have the capability At this time to turn
the spindle on and off? I think I saw something with a drop down that said
a certain pin can go high or low to trigger a relay? If so is that a
12-volt or a 5V trigger and which pin on the motor shield or Arduino board
is the right pin?

You really did a great job with a Web Control! I came to the party late was
this home Maslow thing But I will tell you that it seems from the posts on
the Facebook page for Maslow that most people are still using Ground
Control and that even know I was aware of Web Control, I didn't realize
that it was still being developed where ground control has been dormant for
some time. I don't believe the community of users is really aware of that.
I would would look at GitHub and see different types of calibration schemes
and other things and I couldn't find it in Ground Control or At least it
wasn't developed like it is in Web Control.

Thanks again for your help.

Eric

**Comment by madgrizzle** [comment]
As far as I know, the aux should work as its really a firmware/controller thing vs. a webcontrol thing.  But if there's something I need to do to webcontrol to make it work, I'm happy to work on it.. But I don't have anything with AuxIO's connected.  If someone can troubleshoot the problem, then I'm sure that if its currently being done in Ground Control, we can do it in WebControl.

As for GroundControl vs WebControl, this was a project of mine that just grew and grew.  Unfortunately, I don't have as much free time on my hands as I have in the past, so its not likely I'll be adding many new major things to that I develop on my own, but I certainly want to keep it running and work with people that do want to bring in new features.

**Comment by ersdds** [comment]
I'm not sure what you need to troubleshoot the problem you are talking
about but I would be happy to help if I can. Just let me know what it is
you need and if I can do it, I will.

**Comment by madgrizzle** [comment]
I'd say first post a message on the maslow forums asking if anyone has touch plate working with webcontrol.   If not, then go to Actions->Clear Log Files, try to then use the touch plate, and (assuming it doesn't work), go to Actions->Download Diagnostics File and email it to madgrizzlemaslow at gmail dot com.  The diagnostics file is a zip file that contains your webcontrol.json (equivalent to groundcontrol.ini) and two log files (one log file is an abridged version).

**Comment by madgrizzle** [comment]
I tried it out using my 'fakeservo' controller and webcontrol errored out (said that TouchZ wasn't implemented).  You didn't get an error message when you tried TouchZ?  Regardless, I've added the code to implement it (the function was there, just wasn't able to be called).  It'll be out in the next experimental release.. maybe today/tonight.  Then you can test it with an actual touch plate and see if it works.

**Comment by ersdds** [comment]
Awesome...I tried again today and got the same result. Says it's not implemented. Does it still come off of AUX4? do I have to enable "Fakeservo" or is that just for your "test mode"?

**Comment by ersdds** [comment]
Is there a guide as to what some of the advanced settings are for or what some of the screen displays indicate (Like the error bars)?

**Comment by gb0101010101** [comment]
This is a bug.  Needs addition of code to actions.py:
```
// EXISTING around line 76
            elif msg["data"]["command"] == "moveZ":
                if not self.moveZ(msg["data"]["arg"], float(msg["data"]["arg1"])):
                    self.data.ui_queue1.put("Alert", "Alert", "Error with initiating Z-Axis move.")
// ADD NEW
            elif msg["data"]["command"] == "touchZ":
                if not self.touchZ():
                    self.data.ui_queue1.put("Alert", "Alert", "Error with initiating Z-Axis touch.")
```
It does work on the experimental branch.

**Comment by gb0101010101** [comment]
Thought it was going to take longer to review all the recent commits but it painless.
Here is a PR to fix TouchZ not implemented #128 that adds the code I mentioned above.

**Comment by madgrizzle** [comment]
https://github.com/madgrizzle/WebControl/releases/tag/v0.9333

**Comment by ersdds** [comment]
I apologize for my ignorance. Am I supposed to enter that code someplace or wait for the next update? If I am supposed to do something can you let me know where to look to see the steps involved...In any event thanks for the quick response.

**Comment by madgrizzle** [comment]
The update is there. In webcontrol, go to Help->Update and pick 0.9333 (should be at top). Do you have experimental builds enabled?  If not, go to WebControl Settings-> Enable Experimental Releases.

**Comment by ersdds** [comment]
I do have it enabled. Thanks again I will let you know tomorrow. There is a lot of talk about spindle control. Is that functional now (by controlling a relay) or in the future?

**Comment by madgrizzle** [comment]
Spindle control is a firmware thing.  You include a M3 command in your gcode and it will turn the spindle on if you have the appropriate hardware set up (power relay connected to the Arduino)

**Comment by ersdds** [comment]
Can you give me an idea on the Arduino what pin controls the spindle? Or is it a GPIO setting? I saw in the software under advanced settings where it says spend the automation. I assume the relay high low command is depending upon whether you're normally open and normally close contactor but I'm not sure if the servo is for control of the speed of the spindle? If so does the speed controller go to zero to turn the spindle off? Because I would think if you set the switch to servo you No longer have control of the relay?

**Comment by madgrizzle** [comment]
Check the forums.. I'm not really sure how to hook it up and I know people have done it before.

**Comment by ersdds** [comment]
Thanks

**Comment by ersdds** [comment]
So I tried the new release. There's some good news and some bad news. The good news is it initiates the z-axis to move down. The bad news is I wasn't able to get it to stop when it makes contact. I do have my z-axis turned on. I don't know if there's a software switch that needs to be turned on the GPIO? That seems to be the pin outs from the Arduino and not from the aux 4 on the Maslow motor shield? I even tried touching the two leads together directly but that didn't seem to work and cause the z-axis to stop advancing?

**Comment by madgrizzle** [comment]
Can you create an "Issue" for this?  This is a PR thread that's closed so it doesn't readily show up as an issue to work on.

**Comment by ersdds** [comment]
Sorry to bother you. I'm just not that familiar with GitHub and where to
put things. Thanks for your help.

Eric

**Comment by madgrizzle** [comment]
It's not a problem.  I just get messages on my email with links, but if I try to just find it straight from the web, it's challenging.

**Comment by gb0101010101** [comment]
@ersdds Have a look at:
https://forums.maslowcnc.com/t/automating-z-axis-zeroing/5886

The command to initiate Z Touch is now working, you can see it in the WC console (bottom right), so its probably not a software issue any more.

For hardware issues you are better off asking for support on the [Maslow forum](https://forums.maslowcnc.com).
You should have wires connected to AUX4 on the Maslow board. Make sure you have continuity between the router bit and your touch plate when they are touching.

Use github to report software issue here https://github.com/madgrizzle/WebControl/issues
First search existing issues to see if someone has reported it before. If your issue matches exactly then add your comments to the existing issue.
Otherwise create a new issue.

**Pull request merged**
